### ISSUE TITLE
Reentrancy + DLL call design choices

### ISSUE THREAD

**Issue by thomas-allibe-se** [dnattinger/ni-adv-http-api#2]
Hi,

**"Multithreading safe operations"** is a main argument for this library. However, all VIs are non-reentrant, is it on purpose?
I still can change them to reentrant but what will happen if I update the vip or if I need to distribute the code to my team?
Plus, it uses DLLs,  so debugging will not be worst.

Also, all DLLs are called in UI Thread. I’m not familiar with LabVIEW thread management, but from what I understand, it could lead to UI slowdowns. Am I wrong?

Regards

**Comment by dnattinger** [comment]
Thanks for the feedback @thomas-allibe-se . You're right that the VIs should be reentrant, and you're also right that the Call Library Nodes should be set to 'Run at any thread'. I'm in the process of fixing both issues and hope to get the changes submitted to github today, and a new package uploaded to vipm.io as soon as possible.

**Comment by dnattinger** [comment]
Changes present in _main_ branch and in package build 1.0.1.5 that is now published to vipm.io.
